apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-service
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - image: "users-service:latest"
          imagePullPolicy: Never
          name: users-service-container
          ports:
            - containerPort: 8080
              name: app-port
              protocol: TCP
            - containerPort: 8081
              name: admin-port
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler